file(REAL_PATH CMakeLists.txt DETOURS_TARGET_CMAKELISTS_PATH BASE_DIRECTORY ${DETOURS_SOURCE_DIR})
file(READ ${DETOURS_SOURCE_CMAKELISTS_PATH} CONTENT)

message("${DETOURS_SOURCE_CMAKELISTS_PATH}\n\
${DETOURS_TARGET_CMAKELISTS_PATH}\n\
\n${CONTENT}")

file(WRITE ${DETOURS_TARGET_CMAKELISTS_PATH} ${CONTENT})